from typing import Any, Protocol

from com.sun.star.uno import XInterface

class XPropertySet(XInterface):
    def getPropertySetInfo(self) -> Any: ...
    def getPropertyValue(self, name: str) -> Any: ...
    def setPropertyValue(self, name: str, value: Any) -> None: ...
    def addPropertyChangeListener(self, name: str, listener: Any) -> None: ...
    def removePropertyChangeListener(self, name: str, listener: Any) -> None: ...
    def addVetoableChangeListener(self, name: str, listener: Any) -> None: ...
    def removeVetoableChangeListener(self, name: str, listener: Any) -> None: ...

class XMultiPropertySet(XInterface):
    def getPropertySetInfo(self) -> Any: ...
    def getPropertyValues(self, names: Any) -> Any: ...
    def setPropertyValues(self, names: Any, values: Any) -> None: ...
    def addPropertyChangeListener(self, names: Any, listener: Any) -> None: ...
    def removePropertyChangeListener(self, listener: Any) -> None: ...
    def firePropertyChangeEvent(self, names: Any, listener: Any) -> None: ...

